import React, { useEffect, useState } from 'react'
import { Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Button, Stack, Typography, Box, Divider, TablePagination } from '@mui/material';
import { useTheme } from '@mui/material/styles';
import { useMediaQuery } from '@mui/material';
import { useFetch } from '@/constants/useFetch';
import Navbar from '@/components/Navbar';
import{ useRouter } from 'next/router';
import { useDispatch,useSelector } from 'react-redux';
import { existingData } from '@/features/RTRformslice';
import { useSession} from 'next-auth/react';
import Footer from '@/components/Footer';
import Head from 'next/head';
import useLoginCheck from '@/hooks/useLoginCheck';

const Approveduserlist = () => {

    const {data:session,status} = useSession()
    const router = useRouter()
    const theme = useTheme();
    const isSmallScreen = useMediaQuery(theme.breakpoints.down('sm'));
    const [userList, setUserList] = useState([])
    const dispatch = useDispatch()
    const loginStatus = useSelector((state)=>state.loginForm)
    const { data: check,loading, fetchAPI } = useFetch('get', '/admin/user_list');
    const [adminLoginState,setAdminLoginState] = useState(false)
    const { loginCheck } = useLoginCheck()
    useEffect(() => {
        fetchAPI();
        loginCheck();
    }, [fetchAPI])

    useEffect(() => {
        if (check !== null) {
            setUserList(check.result.list)
        }
    }, [check,dispatch])

    useFetch(()=>{
        setAdminLoginState(true)
    },[loginStatus])
    
    //pagination
    const [page, setPage] = useState(0);
	const [rowsPerPage, setRowsPerPage] = useState(8);

	const handleChangePage = (event, newPage) => {
		setPage(newPage);
	};

	const handleChangeRowsPerPage = (event) => {
		setRowsPerPage(parseInt(event.target.value, 10));
		setPage(0); // Reset to the first page when changing rows per page
	};

	// Calculate the starting index and ending index for the current page
	const startIndex = page * rowsPerPage;
	const endIndex = startIndex + rowsPerPage;

	// Get the current page's data from the 'tender' array
	const currentPageData = userList?.slice(startIndex, endIndex) || [];
         return (
        <>
      <Head>
                <title>Eswatini Environment Authority</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Navbar />           
            <Paper elevation={20} sx={{ width: '98%', mx:'auto', my:'5rem', overflowX: 'auto' }}>
                <Stack spacing={4} direction='column'>
                <Box sx={{ display: 'flex', alignItems:'center'}} >
                        <Typography variant='h1' sx={{ margin: '2.55rem auto', fontSize: '3rem', color: '#2C306F', }}>Approved User List</Typography>
                        {/* <Box sx={{width:{xs:'20%',md:'20%',lg:'15%'}}}>
                        <Button variant='contained' sx={{ background: '#2e7d32 !important' }} onClick={() => router.push('/Admin/ShopList')}>Pending User list</Button>
                        </Box> */}
                    </Box>
                    <TableContainer>
                        <Table sx={{ width: '95%', margin: '0 auto' }}>
                            <TableHead sx={{ ' & th': { px: '5px' } }}>
                                <TableRow sx={{ '&>*': { textAlign: 'center' } }}>
                                    <TableCell >Business Name</TableCell>
                                    <TableCell>Tin</TableCell>
                                    <TableCell>Full Name</TableCell>
                                    <TableCell>Designation</TableCell>
                                    <TableCell>Email Id</TableCell>
                                    <TableCell>Status</TableCell>
                                    <TableCell>Action</TableCell>
                                </TableRow>
                            </TableHead>
                            <TableBody sx={{ ' & td': { px: '5px' } }}>
                                {currentPageData?.map((item, index) => (
                                    <TableRow key={index} sx={{ '&>*': { textAlign: 'center' } }}>
                                        <TableCell>{item.name_of_business}</TableCell>
                                        <TableCell>{item.tin}</TableCell>
                                        <TableCell>{item.first_name}</TableCell>
                                        <TableCell>{item.designation}</TableCell>
                                        <TableCell>{item.email_id}</TableCell>
                                        <TableCell> {item.approval_status === 1
                                            ? "Pending"
                                            : item.approval_status === 2
                                                ? "Approved"
                                                : item.approval_status === 3
                                                    ? "Rejected"
                                                    : ""}</TableCell>
                                        <TableCell>

                                            {/* <CustomButton text="Details" bgColor="#2e7d32" handleClick={() => { console.log(item) }} /> */}
                                            {/* <Button variant='contained' sx={{ background: "#2e7d32 !important" }} component='a' onClick={()=>sendProps(item)}>Details</Button> */}
                                            {/* <Button variant='contained' sx={{ background: "#2e7d32 !important" }} component='a' onClick={()=>router.push('/Admin/RTRDetails/Rtr')}>Details</Button> */}
                                            <Button variant='contained' sx={{ background: "#2e7d32 !important" }}
                                                onClick={() => { router.push({pathname:`/Admin/ApprovalCheck/${item.user_id}`,query:{check:item.approval_status}}) }}>Details</Button>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                        <TablePagination
							rowsPerPageOptions={[5, 10, 25]}
							component="div"
							count={userList?.length || 0}
							rowsPerPage={rowsPerPage}
							page={page}
							onPageChange={handleChangePage}
							onRowsPerPageChange={handleChangeRowsPerPage}
						/>
                    </TableContainer>
                </Stack>
            </Paper>
          
            <Footer/>
        </>
    )
}

export default Approveduserlist

